0 silly input [ 'npm', 'test' ]
1 silly flags { _: [ 'exec' ],
1 silly flags   scope: 'kevoree-group-centralizedws',
1 silly flags   command: 'npm',
1 silly flags   args: [ 'test' ] }
2 verbose rootPath /home/leiko/dev/kevoree/kevoree-js
3 info version 2.0.0
4 info versioning independent
5 silly existsSync /home/leiko/dev/kevoree/kevoree-js/VERSION
6 info scope kevoree-group-centralizedws
7 silly initialize attempt
8 silly initialize success
9 silly execute attempt
10 error exec Errored while executing 'npm test' in 'kevoree-group-centralizedws'
11 error execute Error: Command failed: npm test
11 error execute     at Promise.all.then.arr (/home/leiko/.nvm/versions/node/v6.10.3/lib/node_modules/lerna/node_modules/execa/index.js:210:11)
11 error execute     at process._tickCallback (internal/process/next_tick.js:109:7)
11 error execute  callback with error
11 error execute  { Error: Command failed: npm test
11 error execute     at Promise.all.then.arr (/home/leiko/.nvm/versions/node/v6.10.3/lib/node_modules/lerna/node_modules/execa/index.js:210:11)
11 error execute     at process._tickCallback (internal/process/next_tick.js:109:7)
11 error execute   stack: 'Error: Command failed: npm test\n    at Promise.all.then.arr (/home/leiko/.nvm/versions/node/v6.10.3/lib/node_modules/lerna/node_modules/execa/index.js:210:11)\n    at process._tickCallback (internal/process/next_tick.js:109:7)',
11 error execute   code: 1,
11 error execute   killed: false,
11 error execute   stdout: null,
11 error execute   stderr: null,
11 error execute   failed: true,
11 error execute   signal: null,
11 error execute   cmd: 'npm test',
11 error execute   timedOut: false }
